### ISSUE TITLE
MSVC max macro collides with std::numeric_limits<T>::max

### ISSUE THREAD

**Issue by jancoufal** [pc-john/VulkanTutorial#1]
In the `/VulkanTutorial/10-swapchain/main.cpp` (line 381) the `std::numeric_limits<T>::max` is used, but it collides with `min`/`max` macro defined in the `windows.h` when MSVC compiler is used.

See [Stack owerflow question](https://stackoverflow.com/questions/11544073/how-do-i-deal-with-the-max-macro-in-windows-h-colliding-with-max-in-std).

Can be fixed in `/VulkanTutorial/10-swapchain/CMakeFiles.txt` by adding:
```
if(MSVC)
    add_compile_definitions(NOMINMAX)
endif()
```

**Comment by pc-john** [comment]
What version of Vulkan headers are you using? (Open vulkan.hpp and search for VK_HEADER_VERSION.)

**Comment by jancoufal** [comment]
From the `c:\VulkanSDK\1.2.176.1\Include\vulkan\vulkan.hpp`:
```
static_assert( VK_HEADER_VERSION == 176, "Wrong VK_HEADER_VERSION!" );
```

**Comment by pc-john** [comment]
Thanks. I fixed the problem today in git. I suspected it is the old problem with Vulkan headers of version 130-141, but it turned out to not be the case. You pointed rightly to NOMINMAX solution that I used many times already... I did not append the solution into CMakeLists.txt, as proposed, because my custom is to define it only in files that include windows.h . And windows.h is included by Vulkan headers if VK_USE_PLATFORM_WIN32_KHR is defined. I believe the problem is solved for now. Thanks for reporting it.
